version: "3.5"
services:
  # Install Zookeeper.
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  # Install Kafka.
  kafka:
    container_name: kafka
    image: debezium/kafka:1.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
    - ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_HOST_NAME=kafka
  # Install Postgres.
  postgres:
    container_name: postgres
    image: debezium/postgres:12
    volumes:
    - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
  #Install Kafka Connect.
  kafka-connect:
    container_name: kafka-connect
    image: debezium/connect:1.2
    volumes:
    -./connectors/js-20.2.0.jar:"/$KAFKA_HOME/connectors/js-20.2.0.jar"
    -./connectors/js-scriptengine-20.2.0.jar:"/$KAFKA_HOME/connectors/js-scriptengine-20.2.0.jar"
    ports: 
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
      - postgres
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS=kafka:9092
  #Deploy a Consumer.
  consumer:
    build: .
    container_name: pledge-consumer
    ports:
      - 8101:8080
    image: oawofolu/ssm-pledgeservice:v1
    depends_on:
      - zookeeper
      - kafka
      - postgres